name = "nanodrop-api"
compatibility_date = "2023-01-01"

[durable_objects]
bindings = [
  { name = "DURABLE_OBJECT", class_name = "NanoDrop" } # Binding to our NanoDrop class
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["NanoDrop"]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "nanodrop"
database_id = ""
migrations_dir = "migrations"